Fix : function name for acceleration and deceleration getters
pkerspe/ESP-FlexyStepper pull request #39
Opened 2024-01-14 11:57 UTC by ameisso

2024-01-14 13:18 UTC, pkerspe requested changes
please fix typo in word "deceleration". Then It should be good to merge

2024-01-14 13:18 UTC, pkerspe commented on src/ESP_FlexyStepper.cpp
> +float ESP_FlexyStepper::getConfiguredDescelerationInStepsPerSecondPerSecond()
please fix typo, should be "deceleration"

2024-01-14 13:18 UTC, pkerspe commented on src/ESP_FlexyStepper.cpp
> +float ESP_FlexyStepper::getConfiguredDescelerationInRevolutionsPerSecondPerSecond()
please fix typo, should be "deceleration"

2024-01-14 13:18 UTC, pkerspe commented on src/ESP_FlexyStepper.cpp
> +float ESP_FlexyStepper::getConfiguredDescelerationInMillimetersPerSecondPerSecond()
please fix typo, should be "deceleration"

2024-01-14 13:18 UTC, pkerspe commented on src/ESP_FlexyStepper.h
> +  float getConfiguredDescelerationInStepsPerSecondPerSecond();
please fix typo, should be "deceleration"

2024-01-14 19:09 UTC, ameisso commented
Hello, 


Thanks for the review 
Changes have been made

2024-01-14 19:43 UTC, pkerspe commented
Thanks @ameisso, the typos are fixed,  but in commit 8239eb87854025a4361dc3b408e0b21b88acb311 you additional changes to the code which are still not fixed according to comment. Also this additional change actually does not match the title of this pull request also. I don't mind so much about the title, but the logic should be changed according to comment to prevent dead code / empty code blocks

2024-01-14 19:47 UTC, pkerspe requested changes
see comment about your newly added code block for wdt disabling

2024-01-14 19:47 UTC, pkerspe commented on src/ESP_FlexyStepper.cpp
> +#if ! (CONFIG_IDF_TARGET_ESP32C3 || CONFIG_IDF_TARGET_ESP32S2)
In such a case the whole if statement in the previous line would not make sense, since it would result in an empty block.
Please refactor so that we do not have an empty if block at all. Might need to simply exchange the if / else order.
At the end on such MCUs the function should return false if 1 is given as core number

2024-01-15 13:14 UTC, ameisso commented
Hello, 

changed the block as you asked . 
Thanks for the feedback

2024-01-16 19:49 UTC, pkerspe approved these changes

2024-01-16 19:49 UTC, merged